### ISSUE TITLE
Free time activities bug

### ISSUE THREAD

**Issue by cech12** [DigglesMods/BugFix#12]
Saibantes found bugs in finding free time activities and in the "fun calculation".
https://wiggles.ruka.at/forum/viewtopic.php?f=3&t=326

Maybe the findings can be implemented in this mod.

**Comment by saibantes** [comment]
I would **not** do that.

Yes, some of the "fun calculation" issues look like a bug. However, my changes make the gnomes less unhappy, which appears more like a balancing change than a bugfix. It could be argued that it is intentional that the gnomes loose happiness quicker, this forces you to have better sparetime activities so that this can be compensated.
All in all, the sum of my sparetime changes are somewhere on a spectrum from bugfix to balancing change, drawing a line anywhere is just arbitrary. Therefore I would put none of these changes here into this mod.

This also includes the changes related to the range of the kitchens, which you already put here ...

**Comment by cech12** [comment]
yes, I also think that this issue can be considered fixed by your mod. I also think I'll put the adjustments to the kitchens back into your mod, since, as you say, it's about balancing and less about fixing bugs. :)
